### ISSUE TITLE
Compilation error - Java 9 API used?

### ISSUE THREAD

**Issue by jam01** [opentracing-contrib/java-specialagent#1]
Since we've not yet had a release I tried a `mvn clean install`, got the following:

```
[ERROR] COMPILATION ERROR : 
[INFO] -------------------------------------------------------------
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/Agent.java:[48,28] package com.sun.tools.attach does not exist
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/MethodFingerprint.java:[103,24] cannot find symbol
  symbol:   method compare(java.lang.String[],java.lang.String[])
  location: class java.util.Arrays
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/MethodFingerprint.java:[107,18] cannot find symbol
  symbol:   method compare(java.lang.String[],java.lang.String[])
  location: class java.util.Arrays
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/Agent.java:[86,11] cannot find symbol
  symbol:   class VirtualMachine
  location: class io.opentracing.contrib.specialagent.Agent
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/Agent.java:[86,31] cannot find symbol
  symbol:   variable VirtualMachine
  location: class io.opentracing.contrib.specialagent.Agent
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/ConstructorFingerprint.java:[90,34] cannot find symbol
  symbol:   method compare(java.lang.String[],java.lang.String[])
  location: class java.util.Arrays
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/ConstructorFingerprint.java:[94,18] cannot find symbol
  symbol:   method compare(java.lang.String[],java.lang.String[])
  location: class java.util.Arrays
[INFO] 7 errors 
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] OpenTracing Special Agent .......................... SUCCESS [  0.346 s]
[INFO] opentracing-specialagent ........................... FAILURE [  3.372 s]
[INFO] specialagent-maven-plugin .......................... SKIPPED
[INFO] java-specialagent-rules ............................ SKIPPED
[INFO] opentracing-specialagent-okhttp .................... SKIPPED
[INFO] opentracing-specialagent-jdbc ...................... SKIPPED
[INFO] opentracing-specialagent-concurrent ................ SKIPPED
[INFO] opentracing-specialagent-mongo-driver .............. SKIPPED
[INFO] opentracing-specialagent-web-servlet-filter ........ SKIPPED
[INFO] opentracing-specialagent-camel ..................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 3.920 s
[INFO] Finished at: 2018-12-03T09:10:33-06:00
[INFO] Final Memory: 35M/400M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.7.0:compile (default-compile) on project opentracing-specialagent: Compilation failure: Compilation failure: 
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/Agent.java:[48,28] package com.sun.tools.attach does not exist
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/MethodFingerprint.java:[103,24] cannot find symbol
[ERROR]   symbol:   method compare(java.lang.String[],java.lang.String[])
[ERROR]   location: class java.util.Arrays
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/MethodFingerprint.java:[107,18] cannot find symbol
[ERROR]   symbol:   method compare(java.lang.String[],java.lang.String[])
[ERROR]   location: class java.util.Arrays
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/Agent.java:[86,11] cannot find symbol
[ERROR]   symbol:   class VirtualMachine
[ERROR]   location: class io.opentracing.contrib.specialagent.Agent
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/Agent.java:[86,31] cannot find symbol
[ERROR]   symbol:   variable VirtualMachine
[ERROR]   location: class io.opentracing.contrib.specialagent.Agent
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/ConstructorFingerprint.java:[90,34] cannot find symbol
[ERROR]   symbol:   method compare(java.lang.String[],java.lang.String[])
[ERROR]   location: class java.util.Arrays
[ERROR] /home/jam01/Dev/IntelliJIdea/java-specialagent/opentracing-specialagent/src/main/java/io/opentracing/contrib/specialagent/ConstructorFingerprint.java:[94,18] cannot find symbol
[ERROR]   symbol:   method compare(java.lang.String[],java.lang.String[])
[ERROR]   location: class java.util.Arrays
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :opentracing-specialagent

```

**Comment by SevaSafris** [comment]
@jam01, thank you for filing this issue. I have retrofitted the SpecialAgent code to build on jdk1.8, 9, and 10. Please confirm!
